# Generated by Django 3.1.4 on 2021-10-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(blank=True, upload_to='teachers/profile/')),
                ('email_address', models.CharField(max_length=255, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('room_number', models.CharField(max_length=100, verbose_name='Room Number')),
                ('subjects_taught', models.ManyToManyField(to='teacher_app.Subject')),
            ],
        ),
    ]
